language: 
  - ruby
  
rvm:
  - 2.3.1
  
script:
  - bundle install
  - bundle exec rubocop --format emacs --out tmp/rubocop.txt || true
  - bundle exec brakeman -o tmp/brakeman.json
  - bundle exec brakeman_translate_checkstyle_format translate --file="tmp/brakeman.json" > tmp/brakeman_checkstyle.xml
  - bundle exec scss-lint --no-color --format=Stats --format=Default --out=tmp/scss-lint.txt  app/assets/stylesheets/ || true
  
  - export CI_REPORTS=$PWD/test/reports
  - bundle exec rake minitest test
  
after_script:  
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace publish @.testspace $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}