language: 
  - ruby
  
rvm:
  - 2.2
  
before_install:
# Install Testspace Runner
  - ./testspace_install.sh
  - export PATH="${HOME}/testspace:${PATH}"

script:
  - bundle install
  - bundle exec rake db:migrate
  - bundle exec rake minitest test
  
# Publish Test Results along with Coverage
  - testspace publish [Tests]test/reports/TEST*.xml{test} coverage/coverage.xml ${TESTSPACE_URL}